# fly.toml app configuration file generated for mukmlnkrutka on 2026-04-30T11:17:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mukmlnkrutka'
primary_region = 'fra'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  DB_PATH = '/data/smm_bot.db'
  TZ = 'Asia/Tashkent'

[processes]
  app = 'python bot.py'

[[mounts]]
  source = 'bot_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
