app = 'mukmlnkrutka'
primary_region = 'fra'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  DB_PATH = '/data/smm_bot.db'
  TZ = 'Asia/Tashkent'

[[mounts]]
  source = 'bot_data'
  destination = '/data'

[processes]
  app = 'python main.py'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
